[package]
name = "generator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"
toml = "0.9.7"

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

